//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaleFashion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham_KichThuoc_MauSac
    {
        public string MaSP { get; set; }
        public int MaKT { get; set; }
        public int MaMau { get; set; }
    
        public virtual KichThuoc KichThuoc { get; set; }
        public virtual MauSac MauSac { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
